### PR TITLE
Guestbuttonbox

### PR DESCRIPTION
**Pull request by tingox**
added design files for physical box for the guestbutton door opener. The design files were created by jonnor, and are copied from his repo.

### CODE REVIEW

**Comment by odinho** [comment]
Please center text, you can apply this patch. :)

[center_text.txt](https://github.com/bitraf/bitraf-iot/files/1402757/center_text.txt)

lol github doesn't allow uploading patch files, how tf are you supposed to help out with pull requsets if not? no way to push to this pr sadly:

    To github.com:bitraf/bitraf-iot
     ! [remote rejected] HEAD -> refs/pull/9/head (deny updating a hidden ref)
    error: failed to push some refs to 'git@github.com:bitraf/bitraf-iot'

**Comment by mastensg** [comment]
@odinho
you were not a member of the team https://github.com/orgs/bitraf/teams/members/members

i added you. can you push now?

**Comment by odinho** [comment]
No, GitHub disallows pushing to pull requests :) They even have an error msg for it. I could try pushing to @tingox's repo.

Oh wow, that actually worked.

**Comment by tingox** [comment]
Thanks to @odinho, the patch is now included in the pull request. What happens next?

**Comment by odinho** [comment]
Well you squash and merge it I guess? I really can't be against this, if you've made it, we have it. That's how things are. :P

**Pull request merged**
